"""add Department

Revision ID: 488b1035824d
Revises: 9f4a977079e7
Create Date: 2024-04-10 11:00:16.623468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488b1035824d'
down_revision = '9f4a977079e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
